name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: dfx --version
      - name: Install dependencies
        run: mops install
      - name: run tests
        run: mops test